packages:
  - apps/dashboard
  - apps/docs
  - apps/catalog
  - sdks/javascript
  - sdks/agent-connect
allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@astrojs/starlight@0.42.4'
  - '@astrojs/internal-helpers@0.12.0'
  - '@astrojs/react@7.0.1'
