//! Durable tenant ownership and attempt intent. Credentials, prompts and outputs
//! do not belong in these records. Authorization remains a caller obligation.
use sqlx::{PgPool, postgres::PgPoolOptions};
use uuid::Uuid;
mod accounting;
mod accounts;
mod collectors;
mod observations;
mod operator_audit;
mod operators;
mod vendors;
pub use accounts::{
    AccountHealth, AccountInput, AccountView, AuthMode, BillingMode, QuotaInput, QuotaUnit,
    QuotaView,
};
pub use collectors::CollectorKeyView;
pub use observations::{
    AuthorityEvidenceCounts, CostEvidenceCounts, CostPerAcceptedCompletion, CurrencyAmount,
    ExecutionAccountLink, ExecutionCapacitySummary, ExecutionCharges, ExecutionCohortReport,
    ExecutionCoverageCounts, ExecutionImportSummary, ExecutionOutcomeCounts,
    ExecutionOutcomeEvidenceCounts, ExecutionTaskLink, ExecutionWorkCounts, ImportReceipt,
    NotImportedAccounting,
};
pub use operator_audit::{OperatorAuditActor, OperatorAuditEvent, OperatorAuditPage};
pub use operators::{
    AdminPermission, IssuedOperatorSession, OperatorPrincipal, OperatorRole, OperatorScope,
    OperatorSessionView, OperatorView,
};
pub use vendors::{
    VendorInput, VendorModelInput, VendorModelView, VendorRoute, VendorUpdate, VendorView,
};
mod billing;
mod keys;
mod pricing;
mod providers;
pub use accounting::{
    BudgetSnapshot, CostEntry, GatewayActivityCostSummary, GatewayActivityEntry,
    GatewayActivityFilter, GatewayActivitySummary,
};
pub use keys::{IssuedKey, KeyView, Principal};
pub use pricing::{PriceInput, TokenRates};
pub use providers::{ProviderMembership, ProviderOfferInput};

pub static MIGRATOR: sqlx::migrate::Migrator = sqlx::migrate!();

#[derive(Clone)]
pub struct Store {
    pool: PgPool,
}

#[derive(Clone, Copy)]
pub struct TenantScope {
    pub organization_id: Uuid,
    pub project_id: Uuid,
}

#[derive(sqlx::FromRow, serde::Serialize)]
pub struct NamedResource {
    pub id: Uuid,
    pub name: String,
}

#[derive(sqlx::FromRow, serde::Serialize)]
pub struct WorkspaceResource {
    pub id: Uuid,
    pub name: String,
    pub organization_id: Uuid,
    pub organization_name: String,
}

#[derive(Debug, sqlx::FromRow)]
pub struct Attempt {
    pub id: Uuid,
    pub operation_id: Uuid,
    pub execution: String,
    pub usage_confidence: String,
    pub provider_model: Option<String>,
    pub prompt_tokens: Option<i64>,
    pub completion_tokens: Option<i64>,
    pub settlement: String,
}

/// A validated, unpriced gateway request to admit for upstream dispatch.
/// The operation and attempt identifiers are generated by the gateway before
/// enqueueing so they remain available for response headers after admission.
pub struct GatewayAdmission {
    pub operation_id: Uuid,
    pub attempt_id: Uuid,
    pub scope: TenantScope,
    pub key_id: Uuid,
    pub model: String,
    pub upstream_model: String,
    pub api_base: Option<String>,
    pub task_id: Option<String>,
    pub revision: String,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum GatewayAdmissionStatus {
    Admitted,
    Unauthorized,
    Conflict,
    AccountUnavailable,
}

/// Completion evidence for a previously committed gateway attempt. If this
/// buffered write is lost on process failure, the durable attempt remains
/// `may_have_executed` and therefore visibly unresolved.
#[derive(Clone)]
pub struct GatewayCompletion {
    pub scope: TenantScope,
    pub attempt_id: Uuid,
    pub usage: Option<(u64, u64)>,
    pub provider_model: Option<String>,
}

#[derive(Debug, thiserror::Error)]
pub enum StoreError {
    #[error("invalid execution observation")]
    InvalidObservation,
    #[error("database operation failed")]
    Database(#[from] sqlx::Error),
    #[error("database migration failed")]
    Migration(#[from] sqlx::migrate::MigrateError),
    #[error("record not found in tenant scope or transition already applied")]
    Conflict,
    #[error("token usage exceeds storage range")]
    InvalidUsage,
    #[error("invalid API key configuration")]
    InvalidKey,
    #[error("API key is invalid, expired, revoked, or lacks permission")]
    Unauthorized,
    #[error("invalid price, currency or monetary amount")]
    InvalidPrice,
    #[error("budget has insufficient available funds")]
    BudgetExceeded,
    #[error("usage or execution remains unresolved")]
    Unresolved,
    #[error("invalid account or quota observation")]
    InvalidAccount,
    #[error("account is unavailable or at its concurrency limit")]
    AccountUnavailable,
    #[error("aggregate exceeds the supported numeric range")]
    AggregateOverflow,
    #[error("invalid operator name, role, or session lifetime")]
    InvalidOperator,
    #[error("invalid operator audit cursor or page size")]
    InvalidOperatorAuditQuery,
    #[error("invalid vendor or model configuration")]
    InvalidVendor,
    #[error("database pool size must be positive")]
    InvalidPoolSize,
    #[error("invalid gateway admission batch")]
    InvalidGatewayAdmissionBatch,
}

impl Store {
    pub async fn connect(url: &str) -> Result<Self, StoreError> {
        Self::connect_with_max_connections(url, 10).await
    }

    pub async fn connect_with_max_connections(
        url: &str,
        max_connections: u32,
    ) -> Result<Self, StoreError> {
        if max_connections == 0 {
            return Err(StoreError::InvalidPoolSize);
        }
        let pool = PgPoolOptions::new()
            .max_connections(max_connections)
            .connect(url)
            .await?;
        MIGRATOR.run(&pool).await?;
        Ok(Self { pool })
    }

    pub fn from_pool(pool: PgPool) -> Self {
        Self { pool }
    }

    pub async fn ready(&self) -> Result<(), StoreError> {
        sqlx::query("SELECT 1").execute(&self.pool).await?;
        Ok(())
    }

    pub async fn organizations(&self) -> Result<Vec<NamedResource>, StoreError> {
        Ok(
            sqlx::query_as("SELECT id,name FROM organizations ORDER BY created_at,id LIMIT 1000")
                .fetch_all(&self.pool)
                .await?,
        )
    }
    pub async fn projects(&self, organization_id: Uuid) -> Result<Vec<NamedResource>, StoreError> {
        Ok(sqlx::query_as("SELECT id,name FROM projects WHERE organization_id=$1 ORDER BY created_at,id LIMIT 1000").bind(organization_id).fetch_all(&self.pool).await?)
    }

    pub async fn organization_name(
        &self,
        organization_id: Uuid,
    ) -> Result<Option<String>, StoreError> {
        Ok(
            sqlx::query_scalar("SELECT name FROM organizations WHERE id=$1")
                .bind(organization_id)
                .fetch_optional(&self.pool)
                .await?,
        )
    }

    pub async fn workspaces(
        &self,
        organization_id: Option<Uuid>,
        project_id: Option<Uuid>,
    ) -> Result<Vec<WorkspaceResource>, StoreError> {
        Ok(sqlx::query_as(
            "SELECT p.id,p.name,o.id AS organization_id,o.name AS organization_name FROM projects p JOIN organizations o ON o.id=p.organization_id WHERE ($1::uuid IS NULL OR o.id=$1) AND ($2::uuid IS NULL OR p.id=$2) ORDER BY o.created_at,o.id,p.created_at,p.id LIMIT 1000",
        )
        .bind(organization_id)
        .bind(project_id)
        .fetch_all(&self.pool)
        .await?)
    }

    /// Explicit installation-admin quick setup. Creates both ownership records
    /// atomically and reuses only the designated default, never a name match.
    pub async fn default_workspace(&self) -> Result<TenantScope, StoreError> {
        let mut tx = self.pool.begin().await?;
        sqlx::query("LOCK TABLE default_workspace IN EXCLUSIVE MODE")
            .execute(&mut *tx)
            .await?;
        let existing: Option<(Uuid, Uuid)> = sqlx::query_as(
            "SELECT organization_id, project_id FROM default_workspace WHERE singleton",
        )
        .fetch_optional(&mut *tx)
        .await?;
        let (organization_id, project_id) = match existing {
            Some(scope) => scope,
            None => {
                let organization_id = Uuid::new_v4();
                let project_id = Uuid::new_v4();
                sqlx::query("INSERT INTO organizations (id,name) VALUES ($1,'Personal workspace')")
                    .bind(organization_id)
                    .execute(&mut *tx)
                    .await?;
                sqlx::query("INSERT INTO projects (id,organization_id,name) VALUES ($1,$2,'Default project')")
                    .bind(project_id).bind(organization_id).execute(&mut *tx).await?;
                sqlx::query(
                    "INSERT INTO default_workspace (organization_id,project_id) VALUES ($1,$2)",
                )
                .bind(organization_id)
                .bind(project_id)
                .execute(&mut *tx)
                .await?;
                (organization_id, project_id)
            }
        };
        tx.commit().await?;
        Ok(TenantScope {
            organization_id,
            project_id,
        })
    }

    pub async fn create_organization(&self, name: &str) -> Result<Uuid, StoreError> {
        let id = Uuid::new_v4();
        sqlx::query("INSERT INTO organizations (id, name) VALUES ($1, $2)")
            .bind(id)
            .bind(name)
            .execute(&self.pool)
            .await?;
        Ok(id)
    }

    pub async fn create_project(
        &self,
        organization_id: Uuid,
        name: &str,
    ) -> Result<TenantScope, StoreError> {
        let project_id = Uuid::new_v4();
        sqlx::query("INSERT INTO projects (id, organization_id, name) VALUES ($1, $2, $3)")
            .bind(project_id)
            .bind(organization_id)
            .bind(name)
            .execute(&self.pool)
            .await?;
        Ok(TenantScope {
            organization_id,
            project_id,
        })
    }

    pub async fn create_operation(
        &self,
        scope: TenantScope,
        model: &str,
    ) -> Result<Uuid, StoreError> {
        self.create_operation_for_task(scope, model, None).await
    }

    pub async fn create_operation_for_task(
        &self,
        scope: TenantScope,
        model: &str,
        task_id: Option<&str>,
    ) -> Result<Uuid, StoreError> {
        let id = Uuid::new_v4();
        sqlx::query("INSERT INTO operations (id, organization_id, project_id, model_alias, task_id) VALUES ($1, $2, $3, $4, $5)")
            .bind(id).bind(scope.organization_id).bind(scope.project_id).bind(model).bind(task_id).execute(&self.pool).await?;
        Ok(id)
    }

    /// Persist a gateway request and its first attempt atomically in one
    /// statement. This keeps the pre-dispatch durability boundary while
    /// avoiding a separate database round trip for each row.
    pub async fn prepare_gateway_attempt(
        &self,
        scope: TenantScope,
        model: &str,
        task_id: Option<&str>,
        revision: &str,
    ) -> Result<(Uuid, Uuid), StoreError> {
        let operation_id = Uuid::new_v4();
        let attempt_id = Uuid::new_v4();
        self.prepare_gateway_attempt_with_ids(
            scope,
            operation_id,
            attempt_id,
            model,
            task_id,
            revision,
        )
        .await?;
        Ok((operation_id, attempt_id))
    }

    async fn prepare_gateway_attempt_with_ids(
        &self,
        scope: TenantScope,
        operation_id: Uuid,
        attempt_id: Uuid,
        model: &str,
        task_id: Option<&str>,
        revision: &str,
    ) -> Result<(), StoreError> {
        let _: (Uuid, Uuid) = sqlx::query_as(
            "WITH new_operation AS (\
                INSERT INTO operations (id, organization_id, project_id, model_alias, task_id) \
                VALUES ($1, $2, $3, $4, $5) RETURNING id\
             ), new_attempt AS (\
                INSERT INTO attempts (id, organization_id, project_id, operation_id, resource_id, offer_revision) \
                SELECT $6, $2, $3, new_operation.id, $4, $7 FROM new_operation RETURNING id\
             ) \
             SELECT (SELECT id FROM new_operation), (SELECT id FROM new_attempt)",
        )
        .bind(operation_id)
        .bind(scope.organization_id)
        .bind(scope.project_id)
        .bind(model)
        .bind(task_id)
        .bind(attempt_id)
        .bind(revision)
        .fetch_one(&self.pool)
        .await?;
        Ok(())
    }

    /// Insert operation and attempt rows, recheck admission policy, and commit
    /// dispatch intent for a bounded batch in one database call. The batch
    /// function returns denials as statuses so their durable `not_sent` rows
    /// are retained, matching the single-request admission path.
    pub async fn admit_unpriced_gateway_batch(
        &self,
        admissions: Vec<GatewayAdmission>,
    ) -> Result<Vec<GatewayAdmissionStatus>, StoreError> {
        const MAX_BATCH_SIZE: usize = 64;
        if admissions.is_empty() || admissions.len() > MAX_BATCH_SIZE {
            return Err(StoreError::InvalidGatewayAdmissionBatch);
        }

        let admission_count = admissions.len();
        let mut operation_ids = Vec::with_capacity(admission_count);
        let mut attempt_ids = Vec::with_capacity(admission_count);
        let mut organization_ids = Vec::with_capacity(admission_count);
        let mut project_ids = Vec::with_capacity(admission_count);
        let mut key_ids = Vec::with_capacity(admission_count);
        let mut models = Vec::with_capacity(admission_count);
        let mut task_ids = Vec::with_capacity(admission_count);
        let mut revisions = Vec::with_capacity(admission_count);
        let mut upstream_models = Vec::with_capacity(admission_count);
        let mut api_bases = Vec::with_capacity(admission_count);
        for admission in admissions {
            operation_ids.push(admission.operation_id);
            attempt_ids.push(admission.attempt_id);
            organization_ids.push(admission.scope.organization_id);
            project_ids.push(admission.scope.project_id);
            key_ids.push(admission.key_id);
            models.push(admission.model);
            upstream_models.push(admission.upstream_model);
            api_bases.push(admission.api_base);
            task_ids.push(admission.task_id);
            revisions.push(admission.revision);
        }

        let rows: Vec<(Uuid, String)> = sqlx::query_as(
            "SELECT attempt_id, status FROM niu_admit_unpriced_gateway_batch_with_route(\
                $1, $2, $3, $4, $5, $6, $7, $8, $9, $10\
            )",
        )
        .bind(operation_ids)
        .bind(&attempt_ids)
        .bind(organization_ids)
        .bind(project_ids)
        .bind(key_ids)
        .bind(models)
        .bind(task_ids)
        .bind(revisions)
        .bind(upstream_models)
        .bind(api_bases)
        .fetch_all(&self.pool)
        .await?;

        if rows.len() != admission_count {
            return Err(StoreError::InvalidGatewayAdmissionBatch);
        }
        let mut statuses = std::collections::HashMap::with_capacity(rows.len());
        for (attempt_id, status) in rows {
            let status = match status.as_str() {
                "admitted" => GatewayAdmissionStatus::Admitted,
                "unauthorized" => GatewayAdmissionStatus::Unauthorized,
                "conflict" => GatewayAdmissionStatus::Conflict,
                "account_unavailable" => GatewayAdmissionStatus::AccountUnavailable,
                _ => return Err(StoreError::InvalidGatewayAdmissionBatch),
            };
            if statuses.insert(attempt_id, status).is_some() {
                return Err(StoreError::InvalidGatewayAdmissionBatch);
            }
        }
        attempt_ids
            .iter()
            .map(|admission| {
                statuses
                    .remove(admission)
                    .ok_or(StoreError::InvalidGatewayAdmissionBatch)
            })
            .collect()
    }

    pub async fn prepare_attempt(
        &self,
        scope: TenantScope,
        operation_id: Uuid,
        resource: &str,
        revision: &str,
    ) -> Result<Uuid, StoreError> {
        let id = Uuid::new_v4();
        sqlx::query("INSERT INTO attempts (id, organization_id, project_id, operation_id, resource_id, offer_revision) VALUES ($1, $2, $3, $4, $5, $6)")
            .bind(id).bind(scope.organization_id).bind(scope.project_id).bind(operation_id).bind(resource).bind(revision)
            .execute(&self.pool).await?;
        Ok(id)
    }

    /// Record execution separately from financial settlement. Missing evidence
    /// remains NULL/unknown and explicitly requires reconciliation.
    pub async fn complete(
        &self,
        scope: TenantScope,
        id: Uuid,
        usage: Option<(u64, u64)>,
    ) -> Result<(), StoreError> {
        self.complete_with_provider_model(scope, id, usage, None)
            .await
    }

    pub async fn complete_with_provider_model(
        &self,
        scope: TenantScope,
        id: Uuid,
        usage: Option<(u64, u64)>,
        provider_model: Option<&str>,
    ) -> Result<(), StoreError> {
        let usage = usage
            .map(|(a, b)| {
                Ok::<_, StoreError>((
                    i64::try_from(a).map_err(|_| StoreError::InvalidUsage)?,
                    i64::try_from(b).map_err(|_| StoreError::InvalidUsage)?,
                ))
            })
            .transpose()?;
        let (prompt, completion) = usage.map_or((None, None), |(a, b)| (Some(a), Some(b)));
        let confidence = if usage.is_some() {
            "provider_reported"
        } else {
            "unknown"
        };
        let provider_model = provider_model.map(str::trim).filter(|model| {
            !model.is_empty()
                && model.len() <= 200
                && model.chars().all(|character| !character.is_control())
        });
        let changed = sqlx::query("UPDATE attempts SET execution = 'confirmed_completed', completed_at = now(), usage_confidence = $4, prompt_tokens = $5, completion_tokens = $6, provider_model = $7, settlement = CASE WHEN $4 = 'unknown' THEN 'reconciliation_required' ELSE settlement END WHERE organization_id = $1 AND project_id = $2 AND id = $3 AND execution = 'may_have_executed'")
            .bind(scope.organization_id).bind(scope.project_id).bind(id).bind(confidence).bind(prompt).bind(completion).bind(provider_model)
            .execute(&self.pool).await?.rows_affected();
        if changed != 1 {
            return Err(StoreError::Conflict);
        }
        Ok(())
    }

    /// Persist completion evidence for a bounded set of gateway attempts in
    /// one update. The gateway may enqueue this after returning a provider
    /// response because the earlier durable dispatch intent remains unresolved
    /// if this observation cannot be committed.
    pub async fn complete_gateway_batch(
        &self,
        completions: Vec<GatewayCompletion>,
    ) -> Result<(), StoreError> {
        const MAX_BATCH_SIZE: usize = 64;
        if completions.is_empty() || completions.len() > MAX_BATCH_SIZE {
            return Err(StoreError::InvalidGatewayAdmissionBatch);
        }
        let completion_count = completions.len();
        let mut seen = std::collections::HashSet::with_capacity(completion_count);
        let mut organization_ids = Vec::with_capacity(completion_count);
        let mut project_ids = Vec::with_capacity(completion_count);
        let mut attempt_ids = Vec::with_capacity(completion_count);
        let mut has_usage = Vec::with_capacity(completion_count);
        let mut prompt_tokens = Vec::with_capacity(completion_count);
        let mut completion_tokens = Vec::with_capacity(completion_count);
        let mut provider_models = Vec::with_capacity(completion_count);
        for completion in completions {
            if !seen.insert(completion.attempt_id) {
                return Err(StoreError::InvalidGatewayAdmissionBatch);
            }
            let usage = completion
                .usage
                .map(|(prompt, output)| {
                    Ok::<_, StoreError>((
                        i64::try_from(prompt).map_err(|_| StoreError::InvalidUsage)?,
                        i64::try_from(output).map_err(|_| StoreError::InvalidUsage)?,
                    ))
                })
                .transpose()?;
            organization_ids.push(completion.scope.organization_id);
            project_ids.push(completion.scope.project_id);
            attempt_ids.push(completion.attempt_id);
            has_usage.push(usage.is_some());
            prompt_tokens.push(usage.map(|(prompt, _)| prompt));
            completion_tokens.push(usage.map(|(_, output)| output));
            provider_models.push(completion.provider_model.as_deref().and_then(|model| {
                let model = model.trim();
                (!model.is_empty()
                    && model.len() <= 200
                    && model.chars().all(|character| !character.is_control()))
                .then(|| model.to_owned())
            }));
        }

        let mut tx = self.pool.begin().await?;
        let updated: Vec<Uuid> = sqlx::query_scalar(
            r#"
                WITH input AS MATERIALIZED (
                    SELECT * FROM unnest(
                        $1::uuid[], $2::uuid[], $3::uuid[], $4::boolean[],
                        $5::bigint[], $6::bigint[], $7::text[]
                    ) AS row(organization_id, project_id, attempt_id, has_usage,
                             prompt_tokens, completion_tokens, provider_model)
                )
                UPDATE attempts a
                   SET execution = 'confirmed_completed',
                       completed_at = clock_timestamp(),
                       usage_confidence = CASE WHEN input.has_usage THEN 'provider_reported' ELSE 'unknown' END,
                       prompt_tokens = input.prompt_tokens,
                       completion_tokens = input.completion_tokens,
                       provider_model = input.provider_model,
                       settlement = CASE WHEN input.has_usage THEN a.settlement ELSE 'reconciliation_required' END
                  FROM input
                 WHERE a.organization_id = input.organization_id
                   AND a.project_id = input.project_id
                   AND a.id = input.attempt_id
                   AND a.execution = 'may_have_executed'
                RETURNING a.id
            "#,
        )
        .bind(organization_ids)
        .bind(project_ids)
        .bind(attempt_ids)
        .bind(has_usage)
        .bind(prompt_tokens)
        .bind(completion_tokens)
        .bind(provider_models)
        .fetch_all(&mut *tx)
        .await?;
        if updated.len() != completion_count {
            return Err(StoreError::Conflict);
        }
        tx.commit().await?;
        Ok(())
    }

    pub async fn attempt(
        &self,
        scope: TenantScope,
        id: Uuid,
    ) -> Result<Option<Attempt>, StoreError> {
        Ok(sqlx::query_as("SELECT id, operation_id, execution, usage_confidence, provider_model, prompt_tokens, completion_tokens, settlement FROM attempts WHERE organization_id = $1 AND project_id = $2 AND id = $3")
            .bind(scope.organization_id).bind(scope.project_id).bind(id).fetch_optional(&self.pool).await?)
    }
}
