openapi: 3.1.0
info:
  title: Niu platform configuration API
  version: 0.1.0
servers:
  - url: /
paths:
  /admin/v1/platform/configuration:
    get:
      $ref: './generated/handler-operations.json#/paths/~1admin~1v1~1platform~1configuration/get'
  /admin/v1/platform/payments/integrations:
    get:
      $ref: './generated/handler-operations.json#/paths/~1admin~1v1~1platform~1payments~1integrations/get'
  /admin/v1/platform/payments/epay:
    get:
      $ref: './generated/handler-operations.json#/paths/~1admin~1v1~1platform~1payments~1epay/get'
    put:
      $ref: './generated/handler-operations.json#/paths/~1admin~1v1~1platform~1payments~1epay/put'
