#!/usr/bin/env python3
"""Extract JSON OpenAPI annotations from Rust doc comments; no third-party parser."""

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    paths, names, descriptions = {}, set(), []
    routes = (ROOT / 'apps/gateway/src/web/routes.rs').read_text()
    for source in sorted((ROOT / 'apps/gateway/src').rglob('*.rs')):
        for block in re.findall(r'(?m)^/// ```openapi\n(.*?)^/// ```\s*$', source.read_text(), re.S):
            lines = block.splitlines()
            if not all(line.startswith('/// ') for line in lines):
                raise SystemExit(f'Malformed annotation in {source.relative_to(ROOT)}')
            value = json.loads('\n'.join(line[4:] for line in lines))
            path, method, operation = value['path'], value['method'], value['operation']
            name = operation['operationId']
            if method not in {'get', 'post', 'put', 'patch', 'delete', 'head', 'options'}:
                raise SystemExit(f'Invalid HTTP method: {method}')
            if f'"{path}"' not in routes:
                raise SystemExit(f'Annotated path is not registered: {path}')
            if name in names or method in paths.get(path, {}):
                raise SystemExit(f'Duplicate operation: {name}')
            if operation.get('x-niu-implementation') not in {'implemented', 'stub'}:
                raise SystemExit(f'Missing implementation status: {name}')
            if not operation.get('responses') or not operation.get('description'):
                raise SystemExit(f'Missing response or behavior contract: {name}')
            names.add(name)
            paths.setdefault(path, {})[method] = operation
            descriptions.extend([
                f'## {operation["summary"]}', '', f'`{method.upper()} {path}`', '',
                operation['description'], '',
                f'Implementation: `{operation["x-niu-implementation"]}`. Operation: `{name}`.', '',
                *[f'- HTTP {status}: {response["description"]}' for status, response in operation['responses'].items()], '',
            ])
    if not paths:
        raise SystemExit('No handler annotations found')
    spec = {'openapi': '3.1.0', 'info': {'title': 'Niu annotated handler operations', 'version': '0.1.0'},
            'paths': paths, 'components': {'securitySchemes': {'bearerAuth': {'type': 'http', 'scheme': 'bearer'}}}}
    outputs = {
        'contracts/generated/handler-operations.json': json.dumps(spec, indent=2) + '\n',
        'docs/reference/generated-api-operations.md': '\n'.join([
            '# Annotated API operations', '',
            'Generated by `scripts/extract-handler-openapi.py`. Do not edit directly.', '',
            'This is the annotated subset, not the complete API. See `contracts/openapi.yaml` for the root contract.', '',
            *descriptions,
        ]).rstrip() + '\n',
    }
    for relative, content in outputs.items():
        target = ROOT / relative
        if args.check:
            if not target.exists() or target.read_text() != content:
                raise SystemExit(f'Generated file is stale: {relative}')
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content)
    print(f'Handler annotations: {len(names)} operations; generated contracts are current.')


if __name__ == '__main__':
    main()
