import { useState } from 'react';
import { IconCheck as Check } from "@tabler/icons-react";
import { IconCopy as Copy } from "@tabler/icons-react";
import { IconEye as Eye } from "@tabler/icons-react";
import { IconEyeOff as EyeOff } from "@tabler/icons-react";
import { IconKey as KeyRound } from "@tabler/icons-react";
import { IconPlayerPause as Pause } from "@tabler/icons-react";
import { IconPlayerPlay as Play } from "@tabler/icons-react";
import { IconPlus as Plus } from "@tabler/icons-react";
import { IconPlugConnectedX as Unplug } from "@tabler/icons-react";
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Checkbox } from '@/components/ui/checkbox';
import { Badge } from '@/components/ui/badge';
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '@/components/ui/card';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from '@/components/ui/dialog';
import { agentRequest, base, safeLabel, type Connection } from './data';

export default function Connections({ token, connections, reload }: { token: string; connections: Connection[]; reload: () => void }) {
  const [open, setOpen] = useState(false), [consent, setConsent] = useState(false);
  const [name, setName] = useState('My agent'), [source, setSource] = useState('coding-agent'), [version, setVersion] = useState('0.1.0');
  const [secret, setSecret] = useState<string | null>(null), [copied, setCopied] = useState(false);
  const [revealed, setRevealed] = useState(false);
  const [busy, setBusy] = useState(false), [error, setError] = useState('');
  const [action, setAction] = useState<{ connection: Connection; kind: 'resume' | 'disconnect' } | null>(null);
  const [renew, setRenew] = useState(false);
  async function mutate(fn: () => Promise<unknown>) {
    setBusy(true); setError('');
    try { await fn(); reload(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); }
  }
  return <div className="agent-connections">
    <div className="agent-section-heading"><div><h2>Connections</h2><p>Send execution metadata from an integration you control.</p></div><Button onClick={() => { setConsent(false); setRevealed(false); setError(''); setOpen(true); }}><Plus size={16} />Connect agent</Button></div>
    {error && !open && !action && <p role="alert">{error}</p>}
    <Card><CardHeader><CardTitle>Custom integration</CardTitle><CardDescription>Install the Niu telemetry companion, or instrument your agent with the JavaScript SDK or HTTP API. Keys can write traces only; they cannot read your observations or call model APIs.</CardDescription></CardHeader><CardContent>
      {!connections.length ? <p className="agent-note">No connections yet. Create a connection, send a verification trace, then inspect it in Traces.</p> : <div className="agent-connection-list">{connections.map(c => <div key={c.id} className="agent-connection"><div><strong>{safeLabel(c.name, 'Agent connection')}</strong><p>{safeLabel(c.source, 'Agent')} · Client {safeLabel(c.client_version, 'Unknown version')}</p><p>{c.last_received_at ? `Latest receipt ${new Date(c.last_received_at).toLocaleString()}` : 'Waiting for the first trace'} · Key expires {new Date(c.expires_at).toLocaleDateString()}</p></div><Badge variant="outline">{c.revoked ? 'Disconnected' : c.expired ? 'Expired' : c.paused ? 'Paused' : c.last_received_at ? 'Receiving' : 'Awaiting verification'}</Badge>{!c.revoked && !c.expired && <div className="agent-connection-actions"><Button variant="outline" size="sm" disabled={busy} onClick={() => { if (c.paused) { setRenew(false); setAction({ connection: c, kind: 'resume' }); } else void mutate(() => agentRequest(token, `${base}/connections/${c.id}`, { method: 'PUT', body: JSON.stringify({ paused: true }) })); }}>{c.paused ? <Play size={14} /> : <Pause size={14} />}{c.paused ? 'Resume' : 'Pause'}</Button><Button size="sm" variant="ghost" disabled={busy} onClick={() => { setError(''); setAction({ connection: c, kind: 'disconnect' }); }}><Unplug size={14} />Disconnect</Button></div>}</div>)}</div>}
    </CardContent></Card>
    <Card><CardHeader><CardTitle>Codex <Badge variant="outline">Collection unavailable</Badge></CardTitle><CardDescription>Automatic Codex usage collection is still being qualified. A custom integration does not connect your Codex account.</CardDescription></CardHeader><CardContent><p className="agent-note">No local files to find or upload. Once a supported connection is available, Niu will show its tested client versions and collection coverage before you enable it.</p></CardContent></Card>
    <Card><CardHeader><CardTitle>Data collected</CardTitle></CardHeader><CardContent><p className="agent-note">Run and step labels, observed intervals, reported states, model identities and execution relationships. Optional source-reported token counts and estimates remain attributed to the source. Prompts, outputs, source code, tool payloads and credentials are excluded from trace records. Use labels that contain no sensitive content.</p><p className="agent-note">Traces remain saved until you delete them. Pausing or disconnecting stops ingestion without deleting history. Deletion removes live metadata; operator backups follow the installation’s backup policy.</p></CardContent></Card>
    <Dialog open={open} onOpenChange={value => { setOpen(value); if (!value) { setSecret(null); setCopied(false); } }}><DialogContent className="agent-connection-dialog"><DialogHeader><DialogTitle>{secret ? 'Send your first trace' : 'Connect a custom agent'}</DialogTitle><DialogDescription>{secret ? 'Copy this ingestion key now. Niu will not show it again. Store it securely outside your source code.' : 'This connection receives metadata from your integration. It does not configure or run your agent.'}</DialogDescription></DialogHeader>{secret ? <>
      <Label htmlFor="agent-ingestion-key">Ingestion key · shown once</Label><div className="agent-copy-field"><Input id="agent-ingestion-key" type={revealed ? 'text' : 'password'} readOnly value={secret} autoComplete="off" /><Button variant="outline" aria-label={revealed ? 'Hide ingestion key' : 'Show ingestion key'} onClick={() => setRevealed(v => !v)}>{revealed ? <EyeOff size={16} /> : <Eye size={16} />}</Button><Button variant="outline" aria-label="Copy ingestion key" onClick={async () => { try { await navigator.clipboard.writeText(secret); setCopied(true); } catch { setRevealed(true); setError('Copy is unavailable. Select and copy the key from the field.'); } }}>{copied ? <Check size={16} /> : <Copy size={16} />}</Button></div>
      <p className="agent-note">Set <code>NIU_AGENT_TOKEN</code> privately in your agent’s environment. Install the companion from a Niu release package or build it from source, then verify delivery. The key expires in 90 days.</p><pre className="agent-code">{`export NIU_AGENT_ENDPOINT='${location.origin}${base}'\nexport NIU_AGENT_SOURCE='${source}'\nniu-agent-observability verify\nniu-agent-observability run -- codex\n\n# Optional Claude Code tool hooks: merge into local settings\nniu-agent-observability claude-config`}</pre><p className="agent-note">The wrapper measures process duration and exit status. Claude Code hooks add individual tool traces. Both report partial coverage; neither reads transcripts or measures native Codex tokens.</p><p><a href="/help/concepts/agent-observability/" target="_blank" rel="noreferrer">Installation and telemetry guide</a></p><p className="agent-note">For explicitly instrumented nested traces:</p><pre className="agent-code">{`import { NiuAgentObservabilityClient, NiuExecutionRecorder } from '@niu-io/sdk';\n\nconst client = new NiuAgentObservabilityClient({\n  token: process.env.NIU_AGENT_TOKEN,\n  baseURL: '${location.origin}${base}',\n});\nconst run = new NiuExecutionRecorder({\n  source: '${source}', coverage: 'partial',\n});\nawait run.withSpan('step', {}, async () => {});\nrun.finish('completed');\nawait client.submit({\n  name: 'Connection verification',\n  record: run.export(),\n});`}</pre><p className="agent-note">The SDK is available from the Niu source repository; use the HTTP contract if your installed SDK does not yet expose this client.</p><DialogFooter><Button onClick={() => { setSecret(null); setOpen(false); }}>Done</Button></DialogFooter>
    </> : <form onSubmit={event => { event.preventDefault(); void mutate(async () => { const key = await agentRequest<{ token: string }>(token, `${base}/connections`, { method: 'POST', body: JSON.stringify({ name: name.trim(), source: source.trim(), client_version: version.trim(), consent_version: 'agent-trace-metadata-v1' }) }); setSecret(key.token); }); }} className="agent-form">
      <Label htmlFor="agent-connection-name">Connection name</Label><Input id="agent-connection-name" value={name} maxLength={120} required onChange={e => setName(e.target.value)} />
      <Label htmlFor="agent-source">Source name</Label><Input id="agent-source" value={source} maxLength={64} pattern="[A-Za-z0-9._\-]+" required onChange={e => setSource(e.target.value)} /><p className="agent-note">Use the same source name in your trace records.</p>
      <Label htmlFor="agent-client-version">Client version</Label><Input id="agent-client-version" value={version} maxLength={120} required onChange={e => setVersion(e.target.value)} />
      <div className="agent-consent"><Checkbox id="agent-metadata-consent" checked={consent} onCheckedChange={v => setConsent(v === true)} /><Label htmlFor="agent-metadata-consent">I consent to sending metadata-only traces to my personal Niu account. I will exclude sensitive content from labels.</Label></div>
      {error && <p role="alert">{error}</p>}<DialogFooter><Button type="button" variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button disabled={!consent || busy}><KeyRound size={16} />{busy ? 'Creating…' : 'Create ingestion key'}</Button></DialogFooter>
    </form>}</DialogContent></Dialog>
    <Dialog open={action !== null} onOpenChange={value => { if (!value) setAction(null); }}><DialogContent className="agent-connection-dialog"><DialogHeader><DialogTitle>{action?.kind === 'resume' ? 'Resume metadata collection?' : 'Disconnect this agent?'}</DialogTitle><DialogDescription>{action?.kind === 'resume' ? 'Renew consent before this connection can receive metadata again.' : 'The ingestion key will stop working. Saved traces remain available.'}</DialogDescription></DialogHeader>{action?.kind === 'resume' && <div className="agent-consent"><Checkbox id="agent-renew-consent" checked={renew} onCheckedChange={v => setRenew(v === true)} /><Label htmlFor="agent-renew-consent">I consent to resuming metadata-only trace collection.</Label></div>}{error && <p role="alert">{error}</p>}<DialogFooter><Button variant="outline" onClick={() => setAction(null)}>Cancel</Button><Button disabled={busy || action?.kind === 'resume' && !renew} onClick={() => { if (!action) return; void mutate(async () => { await agentRequest(token, `${base}/connections/${action.connection.id}`, action.kind === 'resume' ? { method: 'PUT', body: JSON.stringify({ paused: false, consent_version: 'agent-trace-metadata-v1' }) } : { method: 'DELETE' }); setAction(null); }); }}>{action?.kind === 'resume' ? 'Resume' : 'Disconnect'}</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}
