import { useState } from 'react';
import { IconArrowUpRight as ArrowUpRight } from "@tabler/icons-react";
import { IconPencil as Pencil } from "@tabler/icons-react";
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '@/components/ui/card';
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from '@/components/ui/table';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from '@/components/ui/dialog';
import { agentRequest, base, duration, dollars, number, safeLabel, type TraceReport, type UsageReport } from './data';

export default function Metrics({ token, traces, usage, from, to, drill, reload }: { token: string; traces: TraceReport; usage?: UsageReport; from: number; to: number; drill: (filters?: { status?: string; day?: string }) => void; reload: () => void }) {
  const [feesOpen, setFeesOpen] = useState(false), [fee, setFee] = useState(''), [overflow, setOverflow] = useState('');
  const [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const hasUsage = usage && BigInt(usage.summary.response_count) > 0n;
  const matchedFees = usage?.fees?.from_ms === from && usage.fees.to_ms === to ? usage.fees : null;
  const maxTraces = Math.max(1, ...traces.by_day.map(d => Number(d.trace_count)));
  const maxTokens = Math.max(1, ...(usage?.by_day ?? []).map(d => Number(BigInt(d.input_tokens) + BigInt(d.output_tokens))));
  async function saveFees() {
    const cents = (value: string) => { if (!value.trim()) return null; if (!/^\d+(\.\d{1,2})?$/.test(value)) throw new Error('Enter a dollar amount with up to two decimal places, or leave it blank for unknown.'); const [a,b=''] = value.split('.'); const result = Number(BigInt(a) * 100n + BigInt(b.padEnd(2, '0'))); if (result > 100_000_000) throw new Error('The fee exceeds the supported amount.'); return result; };
    setBusy(true); setError('');
    try { await agentRequest(token, `${base}/fees`, { method: 'PUT', body: JSON.stringify({ from_ms: from, to_ms: to, subscription_fee_usd_cents: cents(fee), paid_overflow_usd_cents: cents(overflow) }) }); reload(); setFeesOpen(false); } catch (e) { setError((e as Error).message); } finally { setBusy(false); }
  }
  return <div className="agent-metrics">
    <div className="agent-metric-grid">
      <Card><CardHeader><CardDescription>Observed runs</CardDescription><CardTitle>{number(traces.summary.trace_count)}</CardTitle></CardHeader><CardContent><Button variant="link" size="sm" onClick={() => drill()}>Inspect traces <ArrowUpRight size={14} /></Button></CardContent></Card>
      <Card><CardHeader><CardDescription>Observed tokens · Codex</CardDescription><CardTitle>{hasUsage ? number((BigInt(usage!.summary.input_tokens) + BigInt(usage!.summary.output_tokens)).toString()) : 'Unknown'}</CardTitle></CardHeader><CardContent><span className="agent-note">{hasUsage ? `${number(usage!.summary.response_count)} measured responses` : 'No measured usage in this period'}</span></CardContent></Card>
      <Card><CardHeader><CardDescription>Median run duration</CardDescription><CardTitle>{duration(traces.summary.p50_duration_ms)}</CardTitle></CardHeader><CardContent><span className="agent-note">p95 {duration(traces.summary.p95_duration_ms)} · {number(traces.summary.untimed)} untimed</span></CardContent></Card>
      <Card><CardHeader><CardDescription>Reported failed runs</CardDescription><CardTitle>{number(traces.summary.failed)}</CardTitle></CardHeader><CardContent><Button variant="link" size="sm" onClick={() => drill({ status: 'failed' })}>Inspect failures <ArrowUpRight size={14} /></Button></CardContent></Card>
    </div>
    <div className="agent-chart-grid"><Card><CardHeader><CardTitle>Run activity</CardTitle><CardDescription>Observed runs by day · UTC</CardDescription></CardHeader><CardContent>{!traces.by_day.length ? <p className="agent-chart-empty">No trace activity in this period.</p> : <div className="agent-day-chart">{traces.by_day.map(d => <Button key={d.day} variant="ghost" className="agent-day-row" onClick={() => drill({ day: d.day })} aria-label={`Inspect ${number(d.trace_count)} runs on ${d.day}`}><span>{d.day.slice(5)}</span><span className="agent-day-track"><span style={{ width: `${Number(d.trace_count) / maxTraces * 100}%` }} /></span><strong>{number(d.trace_count)}</strong></Button>)}</div>}</CardContent></Card>
    <Card><CardHeader><CardTitle>Token usage</CardTitle><CardDescription>Measured input and output by day · UTC</CardDescription></CardHeader><CardContent>{!usage?.by_day.length ? <p className="agent-chart-empty">No measured token activity in this period.</p> : <div className="agent-day-chart">{usage.by_day.map((d,i) => <div key={`${d.day}:${d.billing_mode}:${i}`} className="agent-day-row"><span>{d.day?.slice(5)}</span><span className="agent-day-track"><span style={{ width: `${Number(BigInt(d.input_tokens) + BigInt(d.output_tokens)) / maxTokens * 100}%` }} /></span><strong>{number((BigInt(d.input_tokens) + BigInt(d.output_tokens)).toString())}</strong></div>)}</div>}</CardContent></Card></div>
    <Card><CardHeader><CardTitle>Execution signals</CardTitle><CardDescription>Reported run states stay separate from failed spans and task acceptance.</CardDescription></CardHeader><CardContent><div className="agent-signal-grid"><div><span>Completed runs</span><strong>{number(traces.summary.completed)}</strong></div><div><span>Failed spans</span><strong>{number(traces.summary.error_count)}</strong></div><div><span>Model calls</span><strong>{number(traces.summary.model_calls)}</strong></div><div><span>Tool calls</span><strong>{number(traces.summary.tool_calls)}</strong></div><div><span>Partial / unknown coverage</span><strong>{number(traces.summary.partial)}</strong></div><div><span>Unknown run state</span><strong>{number(traces.summary.unknown_status)}</strong></div></div></CardContent></Card>
    <Card><CardHeader><div className="agent-section-heading"><div><CardTitle>Subscription value</CardTitle><CardDescription>Estimated public API value of observed subscription usage.</CardDescription></div><Button variant="outline" size="sm" onClick={() => { setFee(matchedFees?.subscription_fee_usd_cents == null ? '' : (matchedFees.subscription_fee_usd_cents / 100).toFixed(2)); setOverflow(matchedFees?.paid_overflow_usd_cents == null ? '' : (matchedFees.paid_overflow_usd_cents / 100).toFixed(2)); setError(''); setFeesOpen(true); }}><Pencil size={14} />Period fees</Button></div></CardHeader><CardContent><div className="agent-signal-grid"><div><span>API-equivalent value</span><strong>{usage && BigInt(usage.comparison.subscription_priced_count ?? '0') > 0n ? `${dollars(usage.comparison.subscription_api_equivalent_usd_nanos)}${BigInt(usage.comparison.subscription_unknown_count ?? '0') > 0n ? ' priced subtotal' : ''}` : 'Unknown'}</strong></div><div><span>Subscription fee</span><strong>{matchedFees?.subscription_fee_usd_cents == null ? 'Unknown' : dollars(String(BigInt(matchedFees.subscription_fee_usd_cents) * 10_000_000n))}</strong></div><div><span>Observed value multiple</span><strong>{usage?.comparison.value_multiple == null ? 'Unavailable' : `${Number(usage.comparison.value_multiple).toFixed(2)}×`}</strong></div><div><span>Paid overflow</span><strong>{matchedFees?.paid_overflow_usd_cents == null ? 'Unknown' : dollars(String(BigInt(matchedFees.paid_overflow_usd_cents) * 10_000_000n))}</strong></div></div><p className="agent-note">Observed usage only; no extrapolation. API-equivalent value is not cash savings or earnings. {hasUsage && BigInt(usage!.summary.unknown_value_count) > 0n ? `${number(usage!.summary.unknown_value_count)} responses have unknown value; the displayed amount is a priced subtotal.` : 'Missing models, token categories and rates remain unknown.'} Fees apply only to this exact period. Workspace charges stay in Workspace Usage.</p></CardContent></Card>
    <Card><CardHeader><CardTitle>Usage by model</CardTitle><CardDescription>Measured Codex usage. Source-reported trace estimates are kept separate.</CardDescription></CardHeader><CardContent>{!usage?.by_model.length ? <p className="agent-note">Model breakdowns appear when qualified usage measurements arrive.</p> : <Table><TableHeader><TableRow><TableHead>Model</TableHead><TableHead>Billing mode</TableHead><TableHead>Responses</TableHead><TableHead>Input</TableHead><TableHead>Cached input</TableHead><TableHead>Output</TableHead><TableHead>API-equivalent value</TableHead></TableRow></TableHeader><TableBody>{usage.by_model.map((m,i) => <TableRow key={i}><TableCell>{safeLabel(m.model, 'Unknown model')}</TableCell><TableCell>{m.billing_mode}</TableCell><TableCell>{number(m.response_count)}</TableCell><TableCell>{number(m.input_tokens)}</TableCell><TableCell>{number(m.cached_input_tokens)}</TableCell><TableCell>{number(m.output_tokens)}</TableCell><TableCell>{BigInt(m.unknown_value_count) > 0n ? BigInt(m.unknown_value_count) === BigInt(m.response_count) ? 'Unknown' : `${dollars(m.priced_value_usd_nanos)} priced subtotal` : dollars(m.priced_value_usd_nanos)}</TableCell></TableRow>)}</TableBody></Table>}</CardContent></Card>
    <Dialog open={feesOpen} onOpenChange={setFeesOpen}><DialogContent><DialogHeader><DialogTitle>Subscription fees for this period</DialogTitle><DialogDescription>{new Date(from).toISOString().slice(0,10)} through {new Date(to - 1).toISOString().slice(0,10)} · UTC. Leave unknown amounts blank.</DialogDescription></DialogHeader><form className="agent-form" onSubmit={e => { e.preventDefault(); void saveFees(); }}><Label htmlFor="agent-subscription-fee">Subscription fee · USD</Label><Input id="agent-subscription-fee" value={fee} inputMode="decimal" onChange={e => setFee(e.target.value)} /><Label htmlFor="agent-overflow-fee">Paid API overflow · USD</Label><Input id="agent-overflow-fee" value={overflow} inputMode="decimal" onChange={e => setOverflow(e.target.value)} />{error && <p role="alert">{error}</p>}<DialogFooter><Button type="button" variant="outline" onClick={() => setFeesOpen(false)}>Cancel</Button><Button disabled={busy}>{busy ? 'Saving…' : 'Save fees'}</Button></DialogFooter></form></DialogContent></Dialog>
  </div>;
}
